In [ ]:
import pandas as pd
import numpy as np
import cv2
from pupil_apriltags import Detector


class Camera():
    def __init__(self):
        self.cam = cv2.VideoCapture(1)
        if(not self.cam.isOpened()):
            print("Camera not found or cannot be opened.")
        
        self.detector = Detector(
            # families="tag16h5",
            # nthreads=4,
            # quad_decimate=1.0,
            # quad_sigma=0.0,
            # refine_edges=1,
            # decode_sharpening=0.25,
            # debug=0
        )

        # Camera parameters (fx, fy, cx, cy)
        self.cam_params = (600, 600, 320, 240)
        self.tag_size_meters = 0.1651 #in meters

    def detect(self):
        self.cam.release()
        cv2.destroyAllWindows()
        self.cam = cv2.VideoCapture(1)
        while True:
            ret, frame = self.cam.read()
            if not ret:
                print("Failed to grab frame")
                return
            print(frame)

            # Needs gray for detections
            gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
            
            cv2.imshow("Camera Frame", frame)

            # Detect AprilTags
            # detections = self.detector.detect(
            #     gray,
            #     estimate_tag_pose=True,
            #     camera_params=self.cam_params,
            #     tag_size=self.tag_size_meters

            # )

            # for det in detections:
            #     print(f"Detected Tag ID: {det.tag_id}")
            #     print(f"Pose (X,Y,Z): {det.pose_t.flatten()}")
        self.cam.release()
        cv2.destroyAllWindows()
        


cam = Camera()
# while True:
    
cam.detect()


[[[185 181 180]
  [184 180 179]
  [184 180 179]
  ...
  [185 166 155]
  [184 167 155]
  [185 168 156]]

 [[184 180 179]
  [184 180 179]
  [183 179 178]
  ...
  [183 164 150]
  [182 163 149]
  [180 162 148]]

 [[183 179 178]
  [183 179 178]
  [182 179 178]
  ...
  [181 161 144]
  [179 159 141]
  [177 158 138]]

 ...

 [[156 157 154]
  [157 158 155]
  [157 158 155]
  ...
  [ 10   8   7]
  [ 10   8   7]
  [ 10   8   7]]

 [[156 159 151]
  [157 159 152]
  [157 159 153]
  ...
  [ 12   9   8]
  [ 11   9   8]
  [ 11   9   8]]

 [[156 159 150]
  [157 160 151]
  [158 161 153]
  ...
  [ 12   9   8]
  [ 11   9   8]
  [ 10   9   8]]]
[[[178 177 170]
  [178 177 170]
  [178 176 169]
  ...
  [181 165 148]
  [178 163 144]
  [175 160 141]]

 [[179 176 171]
  [179 176 171]
  [178 175 170]
  ...
  [177 160 140]
  [174 157 137]
  [173 156 136]]

 [[180 175 173]
  [180 175 173]
  [179 174 172]
  ...
  [174 155 131]
  [175 155 131]
  [176 156 132]]

 ...

 [[150 157 147]
  [150 156 148]
  [150 156 148]
  ..

KeyboardInterrupt: 

: 